name: "Simple Pyright Action"
description: "Run Pyright on your python pull requests."
author: "Jay Jackson"
branding:
    icon: "code"
    color: "green"

inputs:
    github-token:
        description: "GitHub Token"
        required: true

    # Optional
    include-file-comments:
        description: "Include file comments in the output."
        required: false
        default: "true"

runs:
    using: "node20"
    main: "build/index.js"
