name: "Simple Pyright Action"
description: "Run Pyright on your python pull requests."
author: "Jay Jackson"
branding:
    icon: "code"
    color: "green"

inputs:
    # Required
    github-token:
        description: "GitHub Token"
        required: true

    # Optional
    include-file-comments:
        description: "Include file-specific comments on pull requests. Comments are upserted."
        required: false
        default: "true"
    include-base-comparison:
        description: "When this is true, pyright statistics will be calculated for the whole project on both the base and head."
        required: false
        default: "false"
    fail-on-issue-increase:
        description: "When this is true, the action will fail if the number of issues increases from the base to the head."
        required: false
        default: "false"
    pyright-version:
        description: "The npm version of pyright to use."
        required: false
        default: "latest"

runs:
    using: "node20"
    main: "build/index.js"
